import type { KBDocument, UnansweredQuestion } from "@/types/kb";
import type { Conversation, Message } from "@/types/conversation";

// ─── KB Documents ────────────────────────────────────────────────

export const mockKBDocuments: KBDocument[] = [
  {
    id: "doc-1",
    title: "Guide des procédures de création d'entreprise",
    source_url: null,
    category: "Procédures",
    language: "fr",
    content_hash: "abc123",
    file_path: "kb/doc-1/guide-procedures.pdf",
    file_size: 2_450_000,
    chunk_count: 24,
    status: "indexed",
    error_message: null,
    created_at: "2026-03-10T09:00:00Z",
    updated_at: "2026-03-10T09:15:00Z",
  },
  {
    id: "doc-2",
    title: "دليل الاستثمار بجهة الرباط سلا القنيطرة",
    source_url: null,
    category: "Incitations",
    language: "ar",
    content_hash: "def456",
    file_path: "kb/doc-2/guide-investissement-ar.pdf",
    file_size: 1_800_000,
    chunk_count: 18,
    status: "indexed",
    error_message: null,
    created_at: "2026-03-08T14:30:00Z",
    updated_at: "2026-03-08T14:45:00Z",
  },
  {
    id: "doc-3",
    title: "Charte de l'investissement — Loi-cadre 03-22",
    source_url: null,
    category: "Juridique",
    language: "fr",
    content_hash: "ghi789",
    file_path: "kb/doc-3/charte-investissement.pdf",
    file_size: 3_200_000,
    chunk_count: 32,
    status: "indexed",
    error_message: null,
    created_at: "2026-03-05T10:00:00Z",
    updated_at: "2026-03-05T10:30:00Z",
  },
  {
    id: "doc-4",
    title: "FAQ — Incitations fiscales secteur industriel",
    source_url: null,
    category: "Incitations",
    language: "fr",
    content_hash: null,
    file_path: "kb/doc-4/faq-incitations.pdf",
    file_size: 980_000,
    chunk_count: 0,
    status: "indexing",
    error_message: null,
    created_at: "2026-03-25T16:00:00Z",
    updated_at: "2026-03-25T16:00:00Z",
  },
  {
    id: "doc-5",
    title: "Procédure d'obtention du certificat négatif",
    source_url: null,
    category: "Procédures",
    language: "fr",
    content_hash: null,
    file_path: "kb/doc-5/certificat-negatif.pdf",
    file_size: 540_000,
    chunk_count: 0,
    status: "pending",
    error_message: null,
    created_at: "2026-03-26T08:00:00Z",
    updated_at: "2026-03-26T08:00:00Z",
  },
  {
    id: "doc-6",
    title: "Investment Guide — Rabat-Salé-Kénitra Region",
    source_url: null,
    category: "Général",
    language: "en",
    content_hash: "jkl012",
    file_path: "kb/doc-6/investment-guide-en.pdf",
    file_size: 1_200_000,
    chunk_count: 15,
    status: "indexed",
    error_message: null,
    created_at: "2026-02-20T11:00:00Z",
    updated_at: "2026-02-20T11:20:00Z",
  },
  {
    id: "doc-7",
    title: "Régimes douaniers préférentiels — zones franches",
    source_url: null,
    category: "Juridique",
    language: "fr",
    content_hash: null,
    file_path: "kb/doc-7/regimes-douaniers.pdf",
    file_size: 4_100_000,
    chunk_count: 0,
    status: "error",
    error_message: "Failed to extract text from PDF",
    created_at: "2026-03-22T13:00:00Z",
    updated_at: "2026-03-22T13:05:00Z",
  },
  {
    id: "doc-8",
    title: "Offre foncière et zones d'activité économique",
    source_url: null,
    category: "Général",
    language: "fr",
    content_hash: "mno345",
    file_path: "kb/doc-8/offre-fonciere.pdf",
    file_size: 2_750_000,
    chunk_count: 21,
    status: "indexed",
    error_message: null,
    created_at: "2026-03-01T09:30:00Z",
    updated_at: "2026-03-01T09:50:00Z",
  },
];

// ─── Unanswered Questions ────────────────────────────────────────

export const mockUnansweredQuestions: UnansweredQuestion[] = [
  {
    id: "uq-1",
    question: "Quels sont les délais pour obtenir l'autorisation de construire dans la zone industrielle de Kénitra ?",
    language: "fr",
    frequency: 12,
    proposed_answer: "Le délai moyen pour l'obtention de l'autorisation de construire dans la zone industrielle de Kénitra est de 30 jours ouvrables à compter du dépôt du dossier complet.",
    status: "pending",
    reviewed_by: null,
    review_note: null,
    source_conversation_id: "conv-1",
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-20T10:00:00Z",
  },
  {
    id: "uq-2",
    question: "هل يمكن الاستفادة من الإعفاء الضريبي للمقاولات الصغرى؟",
    language: "ar",
    frequency: 8,
    proposed_answer: null,
    status: "pending",
    reviewed_by: null,
    review_note: null,
    source_conversation_id: null,
    created_at: "2026-03-22T14:30:00Z",
    updated_at: "2026-03-22T14:30:00Z",
  },
  {
    id: "uq-3",
    question: "Comment transférer le siège social d'une SARL vers la région RSK ?",
    language: "fr",
    frequency: 5,
    proposed_answer: "Pour transférer le siège social d'une SARL vers la région Rabat-Salé-Kénitra, vous devez déposer un dossier comprenant le PV de l'AGE, les statuts mis à jour, et le certificat négatif de la nouvelle adresse.",
    status: "approved",
    reviewed_by: "admin-1",
    review_note: "Réponse validée",
    source_conversation_id: "conv-3",
    created_at: "2026-03-15T09:00:00Z",
    updated_at: "2026-03-16T10:00:00Z",
  },
  {
    id: "uq-4",
    question: "Existe-t-il un guichet unique pour les investisseurs étrangers ?",
    language: "fr",
    frequency: 15,
    proposed_answer: "Oui, le CRI dispose d'un guichet unique dédié aux investisseurs étrangers offrant un accompagnement personnalisé pour toutes les démarches administratives.",
    status: "modified",
    reviewed_by: "admin-1",
    review_note: "Ajout de précisions sur les horaires",
    source_conversation_id: "conv-1",
    created_at: "2026-03-18T11:00:00Z",
    updated_at: "2026-03-19T09:00:00Z",
  },
  {
    id: "uq-5",
    question: "What are the requirements for opening a branch office in Morocco?",
    language: "en",
    frequency: 3,
    proposed_answer: null,
    status: "rejected",
    reviewed_by: "admin-1",
    review_note: "Hors périmètre CRI",
    source_conversation_id: null,
    created_at: "2026-03-12T16:00:00Z",
    updated_at: "2026-03-13T08:00:00Z",
  },
];

// ─── Conversations ───────────────────────────────────────────────

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    contact_name: "Fatima Zahra El Amrani",
    contact_phone: "+212 661 234 567",
    agent_type: "public",
    status: "active",
    last_message: "Merci pour ces informations. Quels documents dois-je fournir ?",
    last_message_at: "2026-03-26T10:45:00Z",
    unread_count: 2,
  },
  {
    id: "conv-2",
    contact_name: "Youssef Benali",
    contact_phone: "+212 677 890 123",
    agent_type: "public",
    status: "escalated",
    last_message: "Je souhaite parler à un conseiller humain svp",
    last_message_at: "2026-03-26T10:30:00Z",
    unread_count: 1,
  },
  {
    id: "conv-3",
    contact_name: null,
    contact_phone: "+212 650 456 789",
    agent_type: "public",
    status: "closed",
    last_message: "D'accord, merci beaucoup pour votre aide !",
    last_message_at: "2026-03-25T17:20:00Z",
    unread_count: 0,
  },
  {
    id: "conv-4",
    contact_name: "Amina Tazi",
    contact_phone: "+212 612 345 678",
    agent_type: "public",
    status: "active",
    last_message: "ما هي الوثائق المطلوبة لإنشاء شركة؟",
    last_message_at: "2026-03-26T09:15:00Z",
    unread_count: 0,
  },
  {
    id: "conv-5",
    contact_name: "Karim Idrissi",
    contact_phone: "+212 699 111 222",
    agent_type: "internal",
    status: "active",
    last_message: "Quel est le statut du dossier RC-2026-0142 ?",
    last_message_at: "2026-03-26T11:00:00Z",
    unread_count: 3,
  },
  {
    id: "conv-6",
    contact_name: "Sara Bennani",
    contact_phone: "+212 644 567 890",
    agent_type: "public",
    status: "waiting",
    last_message: "J'attends le code OTP pour vérifier mon dossier",
    last_message_at: "2026-03-26T08:50:00Z",
    unread_count: 0,
  },
];

// ─── Messages per conversation ───────────────────────────────────

export const mockMessages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "msg-1-1",
      direction: "inbound",
      type: "text",
      content: "Bonjour, je souhaite créer une entreprise dans la région de Rabat. Quelles sont les étapes ?",
      timestamp: "2026-03-26T10:00:00Z",
      is_read: true,
    },
    {
      id: "msg-1-2",
      direction: "outbound",
      type: "text",
      content: "Bonjour ! Bienvenue au CRI Rabat-Salé-Kénitra. Pour créer une entreprise, voici les étapes principales :\n\n1. Obtention du certificat négatif\n2. Établissement des statuts\n3. Inscription au registre de commerce\n4. Déclaration d'existence fiscale\n5. Affiliation à la CNSS\n\nSouhaitez-vous des détails sur une étape en particulier ?",
      timestamp: "2026-03-26T10:01:00Z",
      is_read: true,
    },
    {
      id: "msg-1-3",
      direction: "inbound",
      type: "text",
      content: "Oui, comment obtenir le certificat négatif ?",
      timestamp: "2026-03-26T10:05:00Z",
      is_read: true,
    },
    {
      id: "msg-1-4",
      direction: "outbound",
      type: "text",
      content: "Le certificat négatif est délivré par l'OMPIC. Vous pouvez faire la demande en ligne sur directinfo.ma ou auprès du guichet unique du CRI.\n\nDocuments requis :\n- Formulaire de demande rempli\n- Copie de la CIN du demandeur\n- 3 propositions de dénomination par ordre de préférence\n\nDélai : 24 à 48h pour la réponse.\nCoût : 230 DH (en ligne) ou 210 DH (guichet).",
      timestamp: "2026-03-26T10:06:00Z",
      is_read: true,
    },
    {
      id: "msg-1-5",
      direction: "inbound",
      type: "text",
      content: "Merci pour ces informations. Quels documents dois-je fournir ?",
      timestamp: "2026-03-26T10:45:00Z",
      is_read: false,
    },
  ],
  "conv-2": [
    {
      id: "msg-2-1",
      direction: "inbound",
      type: "text",
      content: "J'ai un problème avec mon dossier d'investissement",
      timestamp: "2026-03-26T10:00:00Z",
      is_read: true,
    },
    {
      id: "msg-2-2",
      direction: "outbound",
      type: "text",
      content: "Je comprends votre préoccupation. Pourriez-vous me préciser la nature du problème ? S'agit-il d'un retard de traitement, d'un document manquant, ou d'autre chose ?",
      timestamp: "2026-03-26T10:01:00Z",
      is_read: true,
    },
    {
      id: "msg-2-3",
      direction: "inbound",
      type: "text",
      content: "Mon dossier est bloqué depuis 3 semaines et personne ne me répond. C'est inadmissible !",
      timestamp: "2026-03-26T10:10:00Z",
      is_read: true,
    },
    {
      id: "msg-2-4",
      direction: "outbound",
      type: "text",
      content: "Je suis désolé pour ce désagrément. Ce type de situation nécessite l'intervention directe d'un conseiller. Je vais transférer votre conversation à un agent pour un suivi personnalisé.",
      timestamp: "2026-03-26T10:11:00Z",
      is_read: true,
    },
    {
      id: "msg-2-5",
      direction: "outbound",
      type: "system",
      content: "Conversation escaladée vers un agent humain — motif : demande explicite + sujet sensible",
      timestamp: "2026-03-26T10:11:30Z",
      is_read: true,
    },
    {
      id: "msg-2-6",
      direction: "inbound",
      type: "text",
      content: "Je souhaite parler à un conseiller humain svp",
      timestamp: "2026-03-26T10:30:00Z",
      is_read: false,
    },
  ],
  "conv-3": [
    {
      id: "msg-3-1",
      direction: "inbound",
      type: "text",
      content: "Quelles sont les incitations pour le secteur agroalimentaire ?",
      timestamp: "2026-03-25T16:00:00Z",
      is_read: true,
    },
    {
      id: "msg-3-2",
      direction: "outbound",
      type: "text",
      content: "Le secteur agroalimentaire bénéficie de plusieurs incitations dans le cadre de la Charte de l'Investissement :\n\n- Exonération de l'IS pendant 5 ans pour les nouvelles entreprises\n- Aide à l'acquisition du foncier (jusqu'à 20% du coût)\n- Prime à l'emploi de 50 000 DH par emploi stable créé\n- TVA à 0% sur les équipements importés\n\nSouhaitez-vous plus de détails sur l'une de ces mesures ?",
      timestamp: "2026-03-25T16:02:00Z",
      is_read: true,
    },
    {
      id: "msg-3-3",
      direction: "inbound",
      type: "text",
      content: "D'accord, merci beaucoup pour votre aide !",
      timestamp: "2026-03-25T17:20:00Z",
      is_read: true,
    },
    {
      id: "msg-3-4",
      direction: "outbound",
      type: "text",
      content: "Avec plaisir ! N'hésitez pas à nous recontacter si vous avez d'autres questions. Le CRI est à votre disposition. 🇲🇦",
      timestamp: "2026-03-25T17:21:00Z",
      is_read: true,
    },
  ],
  "conv-4": [
    {
      id: "msg-4-1",
      direction: "inbound",
      type: "text",
      content: "السلام عليكم، أريد إنشاء شركة في الرباط",
      timestamp: "2026-03-26T09:00:00Z",
      is_read: true,
    },
    {
      id: "msg-4-2",
      direction: "outbound",
      type: "text",
      content: "وعليكم السلام! مرحباً بكم في المركز الجهوي للاستثمار الرباط-سلا-القنيطرة.\n\nلإنشاء شركة، تحتاجون إلى:\n1. الشهادة السلبية\n2. تحرير النظام الأساسي\n3. التسجيل في السجل التجاري\n4. التصريح بالوجود الضريبي\n\nما هو نوع الشركة التي تودون إنشاءها؟",
      timestamp: "2026-03-26T09:01:00Z",
      is_read: true,
    },
    {
      id: "msg-4-3",
      direction: "inbound",
      type: "text",
      content: "ما هي الوثائق المطلوبة لإنشاء شركة؟",
      timestamp: "2026-03-26T09:15:00Z",
      is_read: true,
    },
  ],
  "conv-5": [
    {
      id: "msg-5-1",
      direction: "outbound",
      type: "system",
      content: "Agent interne identifié — accès lecture seule activé",
      timestamp: "2026-03-26T10:55:00Z",
      is_read: true,
    },
    {
      id: "msg-5-2",
      direction: "inbound",
      type: "text",
      content: "Quel est le statut du dossier RC-2026-0142 ?",
      timestamp: "2026-03-26T11:00:00Z",
      is_read: false,
    },
  ],
  "conv-6": [
    {
      id: "msg-6-1",
      direction: "inbound",
      type: "text",
      content: "Je veux suivre mon dossier",
      timestamp: "2026-03-26T08:30:00Z",
      is_read: true,
    },
    {
      id: "msg-6-2",
      direction: "outbound",
      type: "text",
      content: "Bien sûr ! Pour accéder au suivi de votre dossier, nous devons vérifier votre identité. Un code OTP va être envoyé à votre numéro de téléphone. Veuillez patienter.",
      timestamp: "2026-03-26T08:31:00Z",
      is_read: true,
    },
    {
      id: "msg-6-3",
      direction: "outbound",
      type: "template",
      content: "Votre code de vérification est : ******. Ce code expire dans 5 minutes. Ne le partagez avec personne.",
      timestamp: "2026-03-26T08:31:30Z",
      is_read: true,
    },
    {
      id: "msg-6-4",
      direction: "inbound",
      type: "text",
      content: "J'attends le code OTP pour vérifier mon dossier",
      timestamp: "2026-03-26T08:50:00Z",
      is_read: true,
    },
  ],
};
